### ISSUE TITLE
NPE whe trying to run its reach or flatten

### ISSUE THREAD

**Issue by dvojtise** [lip6/ITSTools#9]
With the newest version of gal 1.0.0.201804131302 (mid april 2018)
when trying to run its reach or to flatten a gal file (such as the one in attachment) we get a Null Pointer Exception

```
java.lang.NullPointerException
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at fr.lip6.move.gal.instantiate.EventCopier.caseVariableReference(EventCopier.java:110)
	at fr.lip6.move.gal.instantiate.EventCopier.caseVariableReference(EventCopier.java:1)
	at fr.lip6.move.gal.util.GalSwitch.doSwitch(GalSwitch.java:305)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at fr.lip6.move.gal.instantiate.EventCopier.caseAssignment(EventCopier.java:233)
	at fr.lip6.move.gal.instantiate.EventCopier.caseAssignment(EventCopier.java:1)
	at fr.lip6.move.gal.util.GalSwitch.doSwitch(GalSwitch.java:239)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at fr.lip6.move.gal.instantiate.EventCopier.caseTransition(EventCopier.java:172)
	at fr.lip6.move.gal.instantiate.EventCopier.caseTransition(EventCopier.java:1)
	at fr.lip6.move.gal.util.GalSwitch.doSwitch(GalSwitch.java:186)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at fr.lip6.move.gal.instantiate.Instantiator.instantiateParameters(Instantiator.java:817)
	at fr.lip6.move.gal.instantiate.Instantiator.instantiateParameters(Instantiator.java:303)
	at fr.lip6.move.gal.instantiate.GALRewriter.instantiateParameters(GALRewriter.java:62)
	at fr.lip6.move.gal.instantiate.GALRewriter.flatten(GALRewriter.java:17)
	at fr.lip6.move.gal.itstools.launch.CommandLineBuilder.buildCommand(CommandLineBuilder.java:62)
	at fr.lip6.move.gal.itstools.launch.ITSLaunchDelegate.launch(ITSLaunchDelegate.java:25)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

[MyBuilding_main_goal_reach.galparam.gal.txt](https://github.com/lip6/ITSTools/files/1943160/MyBuilding_main_goal_reach.galparam.gal.txt)

the previous version (march 2018) was working fine.

**Comment by yanntm** [comment]
sorry Didier, 
I updated instantiation to be much faster for parameters, but I must have broken something.
I'll try to patch asap.

**Comment by yanntm** [comment]
ok should be ok now, sorry for the regression, please close if it patches your problem.

**Comment by yanntm** [comment]
we should setup some unit tests with these models in them

**Comment by dvojtise** [comment]
ok for me with 1.0.0.201804251717 :smile:
